# title of website
title: start_page

# description of website
description: xiehengjian's navigation site

# favicon of website
favicon: "https://github.com/xiehengjian.png?size=40"

# your website url
url: https://xiehengjian.github.io/start_page/

# github profile url
github: "https://github.com/xiehengjian"

# footer message
footer: © 2021-2021 @xiehengjian

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 管理后台
          description: 管理激活码等。
          url: http://admin.yunsi.co:81/
       